/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n3.5-dev-10651-ga64642831e"
#endif /* AVUTIL_FFVERSION_H */
